# Generated by Django 4.0 on 2021-12-28 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='posts',
            name='featured',
            field=models.BooleanField(default=False),
        ),
    ]
