# Generated by Django 4.0 on 2021-12-29 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_rename_posts_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='content',
            field=models.TextField(default='No content available'),
            preserve_default=False,
        ),
    ]
