# Generated by Django 4.0 on 2022-01-06 18:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0009_alter_comment_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='prevoius_post',
            new_name='previous_post',
        ),
    ]
